name: expense_tracker
description: Application to track user's expenses

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_screenutil: 5.8.4
  loggerx: ^1.3.6
  flutter_easyloading: ^3.0.5
  syncfusion_flutter_charts: ^22.2.12
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
