name: expense_tracker
description: Application to track user's expenses

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  loggerx: ^1.3.6
  flutter_easyloading: ^3.0.5
  syncfusion_flutter_charts: ^22.2.12
  fluttertoast: ^8.2.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  dio: ^5.5.0+1
  flutter_pretty_dio_logger: ^3.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  flutter_slidable: ^3.1.1
  intl: ^0.18.1
  firebase_messaging: ^15.0.4
  firebase_core: ^3.3.0
  flutter_local_notifications: ^17.2.2
  speech_to_text: ^6.6.2
  cloud_firestore: ^5.2.1
  flutter_contacts: ^1.1.9+2
  floating_bottom_navigation_bar: ^1.5.2
  permission_handler: ^11.3.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ChatNotzLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/